### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by Alt-Account** [lucxws/deriver-autocatcher#1]
Hey! Mind adding me on discord? cojake4922#6378

I got some cool ideas for this autocatcher to work with pokemons with backgrounds

**Comment by lucxws** [comment]
I've sent you a friend request, but I'm not planning to work with backgrounds since Deriver doesn't have, however, any ideas you got, send it here. 👍

**Comment by Alt-Account** [comment]
Mind adding me again? I don't see you!

**Comment by lucxws** [comment]
Sent!
